---

- name: Install apt-transport-https
  sudo: true
  apt: name=apt-transport-https

- name: Node apt-key
  sudo: true
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Node sources list
  sudo: true
  template:
    src=nodesource.list.j2
    dest=/etc/apt/sources.list.d/nodesource.list

- name: Node apt-get install
  sudo: true
  apt:
    name=nodejs
    update_cache=yes
    state=present

- name: npm apt-get install
  sudo: true
  apt:
    name=npm
    update_cache=yes
    state=present

- name: install mrt
  npm:
    global=yes
    name=meteorite
    state=present
